# Generated by Django 2.2.20 on 2022-01-25 14:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField()),
                ('panchayath', models.CharField(max_length=15)),
                ('ward', models.IntegerField()),
                ('house_no', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
